### ISSUE TITLE
RuntimeError got when trying to read remote file 

### ISSUE THREAD

**Issue by ZM-J** [fnmsd/MySQL_Fake_Server#12]
When I tried to use this to read file, it shows:

```py
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<start_mysql_server.<locals>.cb() done, defined at D:\Anaconda3\envs\py37\lib\asyncio\coroutines.py:118> exception=RuntimeError()>
Traceback (most recent call last):
  File "D:\Anaconda3\envs\py37\lib\asyncio\coroutines.py", line 123, in coro
    res = yield from res
  File "server.py", line 107, in handle_server
    yield from process_fileread(server_reader, server_writer,username[len("fileread_"):])
  File "server.py", line 35, in process_fileread
    fileData = (yield from packet.read())
  File "D:\MySQL_Fake_Server\mysqlproto\protocol\__init__.py", line 62, in read
    self._check_lead(ldata)
  File "D:\MySQL_Fake_Server\mysqlproto\protocol\__init__.py", line 41, in _check_lead
    raise RuntimeError
RuntimeError
```

Why?

**Comment by ZM-J** [comment]
Here is the log:

```
MySQL Fake Server
Author:fnmsd(https://blog.csdn.net/fnmsd)
Load 2 Fileread usernames :[b'linux_passwd', b'linux_hosts']
Load 1 yso usernames :[b'Jdk7u21']
Load 1 Default Files :[b'/etc/passwd']
Start Server at port 3306
Incoming Connection:('127.0.0.1', 64734)
b'Q\x00\x00\x01'
Login Username:fileread_/etc/passwd
b'g\x00\x00\x00'
<= 3
Start Reading File:/etc/passwd
reading file:/etc/passwd
```

**Comment by ZM-J** [comment]
> 目前测MySQL JDBC Connector 5.1.x的版本需要在连接串中加一个maxAllowedPacket=655360属性，否则会报错，有兴趣的师傅可以自己跟一下原因。

啊西八……
