### ISSUE TITLE
ERROR:asyncio:Task exception was never retrieved

### ISSUE THREAD

**Issue by pu3rpuerererererer** [fnmsd/MySQL_Fake_Server#4]
![image](https://user-images.githubusercontent.com/83903820/127437956-b8855b36-6dcd-4943-a7b6-86eea7cf0e8e.png)

```
MySQL Fake Server
Author:fnmsd(https://blog.csdn.net/fnmsd)
Load 8 Fileread usernames :[b'database', b'win_ini', b'win_hosts', b'win', b'linux_passwd', b'linux_hosts', b'index_php', b'ssrf']
Load 1 yso usernames :[b'Jdk7u21']
Load 2 Default Files :[b'/etc/hosts', b'c:\\windows\\system32\\drivers\\etc\\hosts']
Start Server at port 3306
Incoming Connection:('*.*.*.*', 56741)
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-4' coro=<start_mysql_server.<locals>.cb() done, defined at /usr/lib/python3.8/asyncio/coroutines.py:122> exception=RuntimeError()>
Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/coroutines.py", line 127, in coro
    res = yield from res
  File "server.py", line 69, in handle_server
    handshake_response = yield from HandshakeResponse41.read(server_reader.packet(), handshake.capability)
  File "/MySQL_Fake_Server/mysqlproto/protocol/handshake.py", line 64, in read
    data = yield from packet.read()
  File "/MySQL_Fake_Server/mysqlproto/protocol/__init__.py", line 61, in read
    self._check_lead(ldata)
  File "/MySQL_Fake_Server/mysqlproto/protocol/__init__.py", line 40, in _check_lead
    raise RuntimeError
RuntimeError
```

**Comment by fnmsd** [comment]
把_clear去掉试下

**Comment by n5xxxx** [comment]
+1

**Comment by n5xxxx** [comment]
+1

**Comment by XuCcc** [comment]
+1

**Comment by MorIo24** [comment]
https://xz.aliyun.com/news/11457?time__1311=eqGhD5AIxAxUExBwe5t9D7ugjuoGCDmEbD&u_atoken=b0521c6d08f712ea7b2f74e5ab1ff319&u_asig=1a0c399717416886872145283e0034

it may help you

fix it in MySQL_Fake_Server/mysqlproto/protocol/flags.py

**Comment by Jevinliu** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，您的邮件已收到！谢谢！
